image:
    resource: "@ImageBundle/Resources/config/routing.yml"
    prefix:   /

cloud_amazon:
    resource: "@CloudAmazonBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
